#$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), "arescentral"))
$LOAD_PATH.unshift(File.dirname(__FILE__))

puts "Path: #{__FILE__}"

require 'sinatra'
require 'log4r'
require 'log4r/yamlconfigurator'
require 'ohm'
require 'bcrypt'

require 'arescentral/authorization.rb'
require 'arescentral/captcha.rb'
require 'arescentral/exceptions.rb'
require 'arescentral/extensions.rb'
require 'arescentral/api_server.rb'
require 'arescentral/database.rb'
require 'arescentral/http_connector.rb'
require 'arescentral/logger.rb'
require 'arescentral/mailer.rb'
require 'arescentral/secrets.rb'
require 'arescentral/sso.rb'
require 'arescentral/timezones.rb'

require 'arescentral/routes/admin.rb'
require 'arescentral/routes/login.rb'
require 'arescentral/routes/contribs.rb'
require 'arescentral/routes/games.rb'
require 'arescentral/routes/handles.rb'
require 'arescentral/routes/import.rb'
require 'arescentral/routes/game_api.rb'

require 'arescentral/handlers/admin/ban_player_handler.rb'
require 'arescentral/handlers/admin/games_admin_handler.rb'
require 'arescentral/handlers/admin/games_stats_handler.rb'
require 'arescentral/handlers/admin/plugin_create_handler.rb'
require 'arescentral/handlers/admin/plugin_update_handler.rb'
require 'arescentral/handlers/admin/reset_player_password_handler.rb'
require 'arescentral/handlers/admin/update_game_status_handler.rb'

require 'arescentral/handlers/api/api_game_register.rb'
require 'arescentral/handlers/api/api_game_update.rb'
require 'arescentral/handlers/api/api_handle_friends.rb'
require 'arescentral/handlers/api/api_handle_link.rb'
require 'arescentral/handlers/api/api_handle_profile.rb'
require 'arescentral/handlers/api/api_handle_sync.rb'
require 'arescentral/handlers/api/api_handle_unlink.rb'
require 'arescentral/handlers/api/api_plugin_register.rb'
require 'arescentral/handlers/api/api_reset_char_password.rb'

require 'arescentral/handlers/games/games_index_handler.rb'
require 'arescentral/handlers/games/game_detail_handler.rb'

require 'arescentral/handlers/handles/handles_index_handler.rb'
require 'arescentral/handlers/handles/handle_detail_handler.rb'
require 'arescentral/handlers/handles/get_preferences_handler.rb'
require 'arescentral/handlers/handles/save_preferences_handler.rb'
require 'arescentral/handlers/handles/get_friends_handler.rb'
require 'arescentral/handlers/handles/add_friend_handler.rb'
require 'arescentral/handlers/handles/remove_friend_handler.rb'
require 'arescentral/handlers/handles/get_linked_chars_handler.rb'
require 'arescentral/handlers/handles/generate_link_code_handler.rb'
require 'arescentral/handlers/handles/reset_link_password_handler.rb'
require 'arescentral/handlers/handles/unlink_char_handler.rb'

require 'arescentral/handlers/login/login_handler.rb'
require 'arescentral/handlers/login/change_password_handler.rb'
require 'arescentral/handlers/login/register_handler.rb'
require 'arescentral/handlers/login/forgot_password_handler.rb'
require 'arescentral/handlers/login/token_verify_handler.rb'
require 'arescentral/handlers/login/sso_login_handler.rb'

require 'arescentral/handlers/contribs/plugins_index_handler.rb'
require 'arescentral/handlers/contribs/plugin_detail_handler.rb'

require 'arescentral/models/ohm_callbacks.rb'
require 'arescentral/models/ohm_data_types.rb'
require 'arescentral/models/ohm_timestamps.rb'
require 'arescentral/models/object_model.rb'
require 'arescentral/models/friendship.rb'
require 'arescentral/models/game.rb'
require 'arescentral/models/handle.rb'
require 'arescentral/models/linked_char.rb'
require 'arescentral/models/plugin.rb'