source "https://rubygems.org"
 
gem "sinatra", "~> 3.0"
gem "ohm", "~> 3.1"
gem "rspec", "~> 3.7"
#gem 'sendgrid-ruby', "~> 6.6.2"
gem 'mailgun-ruby', '~>1.3.5'

gem 'timezone', "~> 1.3.19"
gem 'thin', "~> 1.8.1"
gem 'bcrypt', "~> 3.1.18"
gem 'logger', "~>1.6.4"
