$LOAD_PATH.unshift(File.join(File.dirname(__FILE__)))

require 'arescentral'

task :start do |t, args|
  AresCentral.start_logger
  web = AresCentral::ApiLoader.new
  web.run
  
end


task :test do |t, args|
  desc "Run all specs."
    require 'rspec/core/rake_task'

    RSpec::Core::RakeTask.new(:spec) do |t|
      t.pattern = 'arescentral/spec/*'
    end
    Rake::Task["spec"].execute
end